import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";
import fs from "fs";

import { sassPlugin } from "esbuild-sass-plugin";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isDirectory = (path) => fs.existsSync(vaultPath) && fs.lstatSync(vaultPath).isDirectory();

const prod = process.argv[2] === "production";

let mainJsPath = "main.js";
let stylesCssPath = "styles.css";

const vaultPath = process.argv[3];

if (isDirectory(vaultPath)) {
  const pluginsDir = path.join(vaultPath, ".obsidian", "plugins");

  if (isDirectory(pluginsDir)) {
    const fileExplorerPlusDir = path.join(pluginsDir, "file-explorer-plus");
    mainJsPath = path.join(fileExplorerPlusDir, "main.js");
    stylesCssPath = path.join(fileExplorerPlusDir, "styles.css");
    const hotreloadFilePath = path.join(fileExplorerPlusDir, ".hotreload");

    fs.closeSync(fs.openSync(hotreloadFilePath, "w"));

    console.log(`Saving to ${fileExplorerPlusDir}`);
  }
}

let jsContext = esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: mainJsPath,
});

let scssContext = esbuild.context({
  entryPoints: ["src/main.scss"],
  outfile: stylesCssPath,
  plugins: [sassPlugin()],
});

[jsContext, scssContext] = await Promise.all([jsContext, scssContext]);

if (prod) {
  await Promise.all([jsContext.rebuild(), scssContext.rebuild()]);
  process.exit(0);
} else {
  await Promise.all([jsContext.watch(), scssContext.watch()]);
}
