name: Feature Request
description: Suggest a new feature for the Unseen Files plugin
labels: ["feature"]
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true

